### ISSUE TITLE
[Feature] 리뷰 별점 평균 / walkfragment MVVM / 리뷰 작성시 이미지 파일 추가 기능 / 필터 적용

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#100]
## Description
리뷰 별점 평균
 walkfragment MVVM 최적화, 리팩토링 일부 
 리뷰 작성시 이미지 파일 추가 기능 
필터 적용(거리)

## Todo
- [X] 리뷰 별점 평균
- [x] 최적화
- [X] 리뷰 작성시 이미지 파일 추가 기능
- [x] 필터 적용(거리) 

## ETC
기타사항
