### ISSUE TITLE
[Feature]place의 이미지,open/close 시간,나머지 정보 가져오기

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#111]
## Description
카카오 restapi에서는 제공되지 않는 이미지 / 영업시간, 나머지 표시할 정보를 구글맵검색을 따로 구현해서
구글맵에서 가져와서 카카오에서 가져온 document와 서로 x,y좌표나 상호명 전화번호 등의 비교를 통해 
구글맵에서 가져온 place와 카카오맵에서 가져온 place가 같은지 확인 후, 구글맵 document에서 필요한 정보를 추출해서
db의 places 문서 내의 필드나 walkfragment,placereviewfragment 등에서 사용

## Todo
- [x] places api 연결
- [x] 구글맵 검색
- [x] document 분기
- [ ] 필터 적용 분기
- [x] place 동일한지 확인
- [ ] db에 추가
- [x] ui에 반영

## ETC
솔직히 얼마나 걸릴지 모르겠습니다.
