### ISSUE TITLE
[Feature] 산책 on 기능 

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#118]
## Description
산책하기 버튼 누르면 시간, 거리 측정 시작 / 맵에 내 위치 표시
산책하기 버튼 누르면 place 마커 전부 제거(onresume 수정?)
산책하기 버튼 누르면 onWalk=true/location에 좌표 업로드 / 종료 누르면 onWalk=false로 업데이트
산책 종료 누르면 산책 리뷰 fragment에서 사진,리뷰 작성 후 db에 업로드
산책하기 버튼 누르면 onWalk=true 상태인 모든 사용자의 정보 받아오기
받아온 사용자의 위치정보와 내 위치정보를 비교해서 일정 거리(기본 2km) 이내에 있으면 마커 찍기
마커 누르면 사용자/반려동물 의 프로필 바텀시트에 표시
바텀시트에 대화하기 누르면 상대방과의 채팅방으로 넘어가기
차단하기 누르면 차단목록에 상대방 추가
필터 기능 구현

## Todo
- [x] 산책하기 버튼 누르면 시간, 거리 측정 시작
- [x] 산책하기 버튼 누르면 place 마커 전부 제거(onresume 수정?)
- [x] 산책하기 버튼 누르면 맵에 내 위치 표시
- [x] 산책하기 버튼 누르면 onWalk=true/location에 좌표 업로드 / 종료 누르면 onWalk=false로 업데이트
- [x] 산책 종료 누르면 산책 리뷰 fragment에서 사진,리뷰 작성 후 db에 업로드
- [x] 산책하기 버튼 누르면 onWalk=true 상태인 모든 사용자의 정보 받아오기
- [x] 받아온 사용자의 위치정보와 내 위치정보를 비교해서 일정 거리(기본 2km) 이내에 있으면 마커 찍기
- [x] 마커 누르면 사용자/반려동물 의 프로필 바텀시트에 표시
- [x] 바텀시트에 대화하기 누르면 상대방과의 채팅방으로 넘어가기
- [x] 차단하기 누르면 차단목록에 상대방 추가
- [ ] 필터 기능

## ETC
최대한 끝낼 수 있도록 해보겠습니다.

고려사항
1. 받아 올려면 서브 컬렉션인 pet도 같이 받아와야 함
2. 필터 기능 활성화->필터 걸러내기 -> 다시 띄울 것을 대비해서 저장해 놓아야 야 한다? 아니면 그냥 다시 검색해서 마커 다시 띄우기?
3. onWalk는 flow로 실시간 업데이트 받아와야함(수정 필요)

**Comment by wktkdandp** [comment]
pet 서브컬렉션 받아와서 출력하기 / 내 위치 핀, 유저 위치 핀 이미지 찾아서 교체 /산책 가능시간 받아서 출력 
users의 userid의 산책기록중에 walkMatchingId이 null이 아닌 문서의 size 가져와서 바텀 시트 매칭 기록:00회 에 출력 
users의 userid의 onwalk ==true인 문서의 서브컬렉션 pet 의 모든 문서 긁어서 제일 첫번째 펫의 정보만 출력
같이 산책하기 누르면 해당 프래그먼트로 상대의 userid넘기기 ( 문서의 제목이 userid라서 레포지토리에 메서드 따로 만들어야함)
차단하기 누르면 해당 프래그먼트로 userid 넘기기 동일
필터 분기 후 적용해서 currentmarkers 지우고 새 마커 띄우기( 깜빡거리는 현상 있는지 확인)
외 다수
