### ISSUE TITLE
[Feature] 사용자 정보 입력화면 ui

### ISSUE THREAD

**Issue by jiheon0212** [APPSCHOOL2-Android/FinalProject-PetPal#13]
## Description
사용자 정보 입력화면 ui 구성하기

## Todo
- [x] circle 이미지 뷰
- [x] 닉네임 및 생년월일 입력 칸
- [x] 생년월일 정보 switch
- [x] 성별 chip
- [x] 산책 가능 시간대 radio or chip
- [x] 다음페이지 이동 button
