### ISSUE TITLE
[Feature] 채팅 메시지 visible 분기

### ISSUE THREAD

**Issue by haehyun-lee** [APPSCHOOL2-Android/FinalProject-PetPal#147]
## Description
하나의 메시지에서 특정 메시지는 특정 사용자에게만 보여야 한다.
e.g. 내가 산책 메이트 요청했으면 그 요청의 수락/거절 메시지가 나에게는 안보여야함

하나의 매칭에 대해 수락/거절은 한 번만 가능하므로 한 번 클릭 이후에는 비활성화되어야 한다.

## Todo
- [x] 채팅 메시지 필터링 (MessageVisibility 해당하는 메시지만 표시)
- [x] 매칭 상태에 따라 산책 메이트 요청 수락, 거절 버튼 활성/비활성 문제 해결
- [x] 산책 메이트 요청 수락, 거절 후 수신측 메시지 숨기기 
- [x] 산책 메이트 요청 후 Snackbar가 메시지 입력칸 가리는 문제 해결
- [x] 산책 메이트 요청 송신측도 자신이 설정한 일시, 장소 확인할 수 있도록 ViewHolder / Message Type 추가
- [x] 차후 매칭 정보 수정 대비해서 산책 메이트 요청 -> 수락 당시의 일시, 장소 텍스트로 기록해두고 표시하는 식으로 변경

## ETC
기타사항
