### ISSUE TITLE
[Feature] 마이페이지 데이터 세팅하기

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#171]
## Description
설명을 작성하세요.

## Todo
- [ ] 산책 기록 세팅하기
- [x] 반려견 recyclerview로 보여주기 
- [ ] 반려견 정보 수정 시 기존 데이터 넣어주기
- [ ] 산책 후기 세팅하기

## ETC
기타사항
