### ISSUE TITLE
[Feature]자잘한 버그 수정/ 유효성 검사/리팩토링

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#180]
## Description
place 리뷰 / 혼자 산책 리뷰(이미지 포함) / 같이 산책 리뷰 유효성 검사
placewritereview MVVM 리팩토링
walk 최적화, MVVM 확인

## Todo
- [ ] place 리뷰
- [ ] 혼자 산책 리뷰(이미지 포함) 
- [ ] 같이 산책 리뷰 유효성 검사
- [ ] placewritereview MVVM 리팩토링
- [ ] walk 최적화, MVVM 확인

## ETC
기타사항
