### ISSUE TITLE
[Feature] 마이페이지 UI 수정

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#25]
## Description
ui 피드백 반영

## Todo
- [x] 다가오는 약속과 매칭기록 붙여주기
- [x] 차단한 사람 관리 페이지 만들기
- [x] 매칭기록 - 어떤 강아지랑 산책한건지 정보 추가, 필터링 추가

## ETC
기타사항
