### ISSUE TITLE
[Feature] 1:1 채팅 기능 구현

### ISSUE THREAD

**Issue by haehyun-lee** [APPSCHOOL2-Android/FinalProject-PetPal#42]
## Description
채팅 기능 구현

## Todo
- [x] 패키지명 변경 chatting -> chat (ChatFragment, item_chat과 통일)
- [x] 시스템 메시지 레이아웃 추가
- [x] 시스템 메시지 ViewHolder 추가
- [x] 채팅창 RecyclerView에 채팅 + 시스템 메시지 함께 표시하기
- [x] 1:1 채팅 기능 구현

## ETC
기타사항
