### ISSUE TITLE
[Feature] 자잘한 수정사항

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#61]
## Description
화면 점검 후 생긴 수정사항

## Todo
- [x] 사용자 정보 입력-> 수정으로 바꾸기, 반려견 정보 입력-> 수정으로 바꾸기, 등록하기 버튼 문구 수정
- [x] 남아 여아 버튼 하나만 선택되도록, 중성화 버튼도
- [x] 매칭기록 필터링 -> 사진으로 변경
- [x] 상세 산책기록에 시간, 거리 단위 추가
- [x] 지도 숫자 색깔 이상함

## ETC
기타사항
