### ISSUE TITLE
[Feature] 채팅, 문의 ui 수정

### ISSUE THREAD

**Issue by haehyun-lee** [APPSCHOOL2-Android/FinalProject-PetPal#62]
## Description
피드백 수정사항 적용

## Todo
- [x] 채팅 입력창 잘리는 부분 여백 추가
- [x] FAQ 카테고리 필터링
- [x] 1:1문의 문의 상태 TextView 전환

## ETC
기타사항
