### ISSUE TITLE
[Feature]커뮤니티, 상품 등록 페이지 UI 수정

### ISSUE THREAD

**Issue by kimjinsub1217** [APPSCHOOL2-Android/FinalProject-PetPal#65]
## Description
커뮤니티, 상품 등록 페이지 UI 수정

## Todo
- [x] 커뮤니티 UI 수정
- [x] 상품 등록 페이지 UI 수정
- [x] 네비게이션 화면 전환 애니메이션

## ETC
기타사항
