### ISSUE TITLE
[Feature]db에 카카오api로 받아온 방문지 + 리뷰 등록 / 등록된 리뷰/ 갯수 받아서 출력

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#71]
## Description
방문지 + 첫 리뷰 작성시 db에 placeid로 place 등록(placereview까지) 
등록된 리뷰 정보중 최신순으로 내림차순해서 2개 받아와서 place bottom sheet에 출력
총 리뷰 개수 카운트 후 받아서 출력

## Todo
- [x] db에 place,placereview 등록
- [x] 등록된 리뷰 받아오기
- [x] 리뷰 개수 받아서 출력

## ETC
기타사항
