### ISSUE TITLE
[Feature] 산책 후기 보기 화면 ui

### ISSUE THREAD

**Issue by haehyun-lee** [APPSCHOOL2-Android/FinalProject-PetPal#83]
## Description
산책 후기 관련 ui 마무리

## Todo
- [x] 산책 후기 보내기 화면 ui 수정
- [x] 산책 후기 보기 화면 ui
- [x] 마이페이지 > 산책 후기 보기 연결

## ETC
기타사항
