### ISSUE TITLE
[Feature] 현재 위치로 가기 기능 / 화면 이동(bottom sheet,fragment) 후 walkfragment로 복귀나 앱 백그라운드에서 재진입시 마지막 위치로 mapcenter 이동 , 검색 후 마커 표기 /place의 리뷰가 1개면 ui 간격 불균일 수정 

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-PetPal#85]
## Description
현재 위치로 가기 버튼,기능
화면 이동(bottom sheet,fragment) 후 walkfragment로 복귀나 앱 백그라운드에서 재진입시 
마지막 위치로 mapcenter 이동 , 검색 후 마커 표기 
place의 리뷰가 1개면 바텀시트의 리뷰와 버튼과의 간격 불균일 ,ui 배치 수정

## Todo
- [x] 현재 위치로 가기 버튼,기능
- [x] 마지막 위치로 mapcenter 이동->검색,마커
- [x] place의 리뷰가 1개면 버튼과의 간격,ui 배치 수정

## ETC
기타사항
