### ISSUE TITLE
[Feature] 사용자 정보, 반려견 정보 저장하기

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#98]
## Description
사용자 정보, 반려견 정보 저장하기

## Todo
- [x] 사용자 정보 저장
- [x] 반려견 정보 저장
- [x] 반려견 정보 저장할 때 사용자 정보 한방에 저장하기
- [x] 백스택 관리하기
- [x] 로그아웃 시 백스택
- [x] 사용자 정보 있는 상태에서 로그인시 백스택
- [x] 반려견 정보 입력 후 가입 및 로그인시 백스택
- [x] 가입 및 반려견 정보 입력 후 백스택
